### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by RichardLitt** [reshufflehq/reshuffle-monday-salesforce-example#1]
Good work! This repo needs a license, though. MIT?

**Comment by foundingnimo** [comment]
Hey - thanks @RichardLitt - the license is stated inside the `package.json` file, but we'll add the license into the repo as well.

**Comment by RichardLitt** [comment]
Sweet. Yeah, I don't think that the license applies unless the actual text is included. However, I am not a lawyer.

**Comment by foundingnimo** [comment]
> Sweet. Yeah, I don't think that the license applies unless the actual text is included. However, I am not a lawyer.

Neither am I :) 
Interestingly - [Reading on GH](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository) - seems like it might be enough to declare in `package.json` - but I like things to be tidy and explicit - so thanks for pointing this out!
